# project-registry:start
x-project-registry:
  name: dailywave
  port: 9008
  env: prod
  updated_at: 2026-01-12T16:55:02Z
# project-registry:end

services:
  backend:
    build: ./backend
    ports:
      - "8020:8020"
    volumes:
      - ./backend/data:/app/data
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3020:3020"
    restart: always
